apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: auth
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
        - name: authentication-connect
          image: ashwiin11/connect-auth
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://db-service:3306/login"
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: database
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    name: auth
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

