version : '3.8'
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE : login
      MYSQL_ROOT_PASSWORD : database
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      authentication:
  adminer:
    image: adminer
    restart: always
    ports:
      - "9000:8080"
    depends_on:
      - db
    networks:
      authentication:
  spring-boot-app:
    container_name: authentication-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/login?allowPublicKeyRetrieval=true
    depends_on:
      - db
    networks:
      authentication:
    restart: on-failure
volumes:
  mysql:
    driver: local
networks:
  authentication: